import { Asset } from '../collections';
import { LevelInterface } from '../interfaces';
import { Chunk, Tile } from '../models';

export const Overworld: LevelInterface = {
  chunks: [
    [new Chunk([
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
      [new Tile(Asset.TileWaterGrassBottom), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileGrass1), new Tile(Asset.TileWaterGrassTop)],
    ])]
  ]
};
